version: "3.8"

services:
  keycloakpaymentsintegrationpostgres:
    hostname: keycloakpaymentsintegrationpostgres
    image: postgres
    expose:
      - 5432
    ports:
      - 7346:5432
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    volumes:
      - /Users/japhethelijah/dev/docker-volumes/payments-integration/keycloak/postgresql/data:/var/lib/postgresql/data

  keycloakpaymentsintegration:
    build:
      context: .
      dockerfile: Dockerfile
    image: jw/keycloakpaymentsintegration:1
    expose:
      - 8080
    ports:
      - 7347:8080
    environment:
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      # - KC_DB_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      # - KC_DB_URL=jdbc:postgresql://${KC_DB}/${POSTGRES_DB}
      - KC_DB_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
    restart: unless-stopped
    entrypoint: ["sh", "//opt/keycloak/bin/kc.sh","start-dev"]
    volumes:
      - /Users/japhethelijah/dev/docker-volumes/payments-integration/keycloak/server/conf:/conf
      